language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - 8.2
  - 8.3

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""
before_script:
  - travis_retry composer update ${COMPOSER_FLAGS}
script:
  - vendor/bin/phpunit